/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainGuideRouteImport } from './routes/train-guide'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BudgetCalculatorRouteImport } from './routes/budget-calculator'
import { Route as IndexRouteImport } from './routes/index'

const TrainGuideRoute = TrainGuideRouteImport.update({
  id: '/train-guide',
  path: '/train-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetCalculatorRoute = BudgetCalculatorRouteImport.update({
  id: '/budget-calculator',
  path: '/budget-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget-calculator': typeof BudgetCalculatorRoute
  '/contact': typeof ContactRoute
  '/itineraries': typeof ItinerariesRoute
  '/train-guide': typeof TrainGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget-calculator': typeof BudgetCalculatorRoute
  '/contact': typeof ContactRoute
  '/itineraries': typeof ItinerariesRoute
  '/train-guide': typeof TrainGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget-calculator': typeof BudgetCalculatorRoute
  '/contact': typeof ContactRoute
  '/itineraries': typeof ItinerariesRoute
  '/train-guide': typeof TrainGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget-calculator'
    | '/contact'
    | '/itineraries'
    | '/train-guide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/budget-calculator' | '/contact' | '/itineraries' | '/train-guide'
  id:
    | '__root__'
    | '/'
    | '/budget-calculator'
    | '/contact'
    | '/itineraries'
    | '/train-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetCalculatorRoute: typeof BudgetCalculatorRoute
  ContactRoute: typeof ContactRoute
  ItinerariesRoute: typeof ItinerariesRoute
  TrainGuideRoute: typeof TrainGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train-guide': {
      id: '/train-guide'
      path: '/train-guide'
      fullPath: '/train-guide'
      preLoaderRoute: typeof TrainGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-calculator': {
      id: '/budget-calculator'
      path: '/budget-calculator'
      fullPath: '/budget-calculator'
      preLoaderRoute: typeof BudgetCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetCalculatorRoute: BudgetCalculatorRoute,
  ContactRoute: ContactRoute,
  ItinerariesRoute: ItinerariesRoute,
  TrainGuideRoute: TrainGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
